apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 5
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: app:v1
        ports:
        - containerPort: 8000
