---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: backend-service
            port:
              number: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-files-config
data:
  important-file: |
    This is a very important file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 4
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: app:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://admin:admin@db-service:5432/workshop-k8s
        volumeMounts:
        - name: static-files
          mountPath: /src/app/static
      volumes:
        - name: static-files
          configMap:
            name: static-files-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: app:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://admin:admin@db-service:5432/workshop-k8s
        volumeMounts:
        - name: static-files
          mountPath: /src/app/static/canary-file
          subPath: important-file
      volumes:
        - name: static-files
          configMap:
            name: static-files-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:17.0-alpine3.20
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: workshop-k8s
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
    ports:
    - protocol: TCP
      port: 5432
